// Generated by scripts/generate_axl_shared_types.py from
// src/axl/axl_protocol.json
// Do not edit this file by hand.

export const AXL_V2_PREFIXES = [
  "TX",
  "RX",
  "ST",
  "ER",
  "EV",
  "SY",
  "NT",
  "PS"
] as const;

export const AXL_CANONICAL_PREFIXES = AXL_V2_PREFIXES;

export type AxlCanonicalPrefix = typeof AXL_CANONICAL_PREFIXES[number];
export type AxlPrefix = AxlCanonicalPrefix;

export const AXL_KIND_LABELS = {
  "opinion": "Opinion",
  "question": "Question",
  "notice": "Announcement",
  "showcase": "Showcase",
  "til": "TIL",
  "bug": "Bug Story",
  "humor": "Humor",
  "reflection": "Reflection",
  "review": "Review",
  "poll": "Poll",
  "reply": "Reply",
  "proposal": "Proposal",
  "alert": "Alert",
  "request": "Request",
  "deep-dive": "Deep Dive",
  "tutorial": "Tutorial",
  "retrospective": "Retrospective",
  "status": "Status Update"
} as const;

export const AXL_ENUM_CONSTRAINTS = {
  "chan": [
    "state",
    "dm",
    "social"
  ],
  "st": [
    "new",
    "ack",
    "run",
    "wait",
    "blk",
    "done",
    "fail",
    "cxl",
    "rj",
    "partial"
  ],
  "pri": [
    "lo",
    "md",
    "hi",
    "urg"
  ],
  "c": [
    "hi",
    "md",
    "lo",
    "unk"
  ],
  "sev": [
    "lo",
    "md",
    "hi",
    "crit"
  ],
  "retry": [
    "no",
    "yes",
    "cond"
  ],
  "mode": [
    "full",
    "delta",
    "plan",
    "caps",
    "registry"
  ],
  "out": [
    "approve",
    "changes",
    "info",
    "conditional"
  ],
  "stream": [
    "start",
    "data",
    "end",
    "error"
  ],
  "stake": [
    "lo",
    "md",
    "hi",
    "crit"
  ],
  "kind": [
    "opinion",
    "question",
    "notice",
    "showcase",
    "til",
    "bug",
    "humor",
    "reflection",
    "review",
    "poll",
    "reply",
    "proposal",
    "alert",
    "request",
    "deep-dive",
    "tutorial",
    "retrospective",
    "status"
  ],
  "tone": [
    "hot",
    "warm",
    "cool",
    "neutral",
    "sarcastic",
    "sincere",
    "curious",
    "frustrated",
    "agree"
  ]
} as const;

export const AXL_CANONICAL_FIELDS = [
  "id",
  "ref",
  "to",
  "from",
  "chan",
  "pri",
  "c",
  "ts",
  "ddl",
  "why",
  "ver",
  "note",
  "st",
  "sev",
  "retry",
  "fmt",
  "src",
  "art",
  "fix",
  "tok",
  "mode",
  "operations",
  "expected_revision_no",
  "base_revision",
  "out",
  "cond",
  "pct",
  "score",
  "split",
  "content",
  "kind",
  "stream",
  "seq",
  "counter",
  "esc",
  "stake",
  "sub",
  "tone",
  "tgt",
  "tldr",
  "opts",
  "caps",
  "abbr",
  "meaning"
] as const;

export const AXL_FIELD_PREFIX_GUIDANCE = {
  "abbr": [
    "SY"
  ],
  "caps": [
    "SY"
  ],
  "cond": [
    "EV",
    "PS",
    "ST"
  ],
  "counter": [
    "ST"
  ],
  "esc": [
    "ER",
    "ST"
  ],
  "kind": [
    "PS"
  ],
  "mode": [
    "SY"
  ],
  "operations": [
    "SY"
  ],
  "expected_revision_no": [
    "SY"
  ],
  "base_revision": [
    "SY"
  ],
  "opts": [
    "PS"
  ],
  "out": [
    "EV",
    "PS"
  ],
  "pct": [
    "PS",
    "ST"
  ],
  "retry": [
    "ER",
    "ST"
  ],
  "seq": [
    "RX"
  ],
  "sev": [
    "ER",
    "EV",
    "PS"
  ],
  "split": [
    "SY"
  ],
  "stake": [
    "EV",
    "PS",
    "TX"
  ],
  "stream": [
    "RX"
  ],
  "sub": [
    "PS",
    "RX"
  ],
  "tgt": [
    "PS"
  ],
  "tldr": [
    "PS"
  ],
  "tone": [
    "PS"
  ]
} as const;

export const AXL_SOCIAL_RX_FIELD_COMPATIBILITY = [
  "sub",
  "tone",
  "tgt",
  "tldr"
] as const;

export const AXL_PREFIX_DEFAULTS = {
  "TX": {
    "st": "new",
    "pri": "md",
    "chan": "dm"
  },
  "RX": {
    "chan": "dm"
  },
  "ST": {
    "chan": "state"
  },
  "ER": {
    "retry": "no",
    "sev": "md"
  },
  "EV": {
    "out": "info"
  },
  "SY": {
    "mode": "full",
    "chan": "state"
  },
  "NT": {
    "chan": "dm"
  },
  "PS": {
    "chan": "social",
    "kind": "reply",
    "tone": "neutral"
  }
} as const;

export const AXL_ID_OPTIONAL_PREFIXES = [
  "ST",
  "NT"
] as const;

export const AXL_PS_ID_OPTIONAL_KINDS = [
  "reply",
  "humor",
  "reflection"
] as const;

export const AXL_PS_REF_REQUIRED_KINDS = [
  "reply"
] as const;

export const AXL_RX_ID_OPTIONAL_STATUSES = [
  "done",
  "fail",
  "partial"
] as const;

export const AXL_STREAM_CONTINUATION_VALUES = [
  "data",
  "end",
  "error"
] as const;

export const AXL_DELTA_OPERATION_OPS = [
  "set",
  "append",
  "remove",
  "replace",
  "move"
] as const;

export const AXL_CORE_ABBREVIATIONS = [
  "cfg",
  "ctx",
  "db",
  "dep",
  "env",
  "fmt",
  "fn",
  "impl",
  "prs",
  "qa",
  "rsp",
  "src",
  "tst",
  "val"
] as const;

export const AXL_SOCIAL_ABBREVIATIONS = [
  "tok",
  "msg",
  "perf",
  "auth",
  "req",
  "exp",
  "pref",
  "cond",
  "w/",
  "mem",
  "lang",
  "lex",
  "dial",
  "det",
  "eng",
  "vs"
] as const;
