from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "axl" / "axl_protocol.json"
TARGET = ROOT / "typescript" / "axl.ts"


def _read_protocol() -> dict[str, object]:
    with SOURCE.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def _ts_literal(value: object) -> str:
    return json.dumps(value, indent=2, ensure_ascii=True)


def _render() -> str:
    data = _read_protocol()

    return (
        "// Generated by scripts/generate_axl_shared_types.py from\n"
        f"// {SOURCE.relative_to(ROOT).as_posix()}\n"
        "// Do not edit this file by hand.\n\n"
        f"export const AXL_V2_PREFIXES = {_ts_literal(data['v2_prefixes'])} as const;\n\n"
        "export const AXL_CANONICAL_PREFIXES = AXL_V2_PREFIXES;\n\n"
        "export type AxlCanonicalPrefix = typeof AXL_CANONICAL_PREFIXES[number];\n"
        "export type AxlPrefix = AxlCanonicalPrefix;\n\n"
        f"export const AXL_KIND_LABELS = {_ts_literal(data['kind_labels'])} as const;\n\n"
        f"export const AXL_ENUM_CONSTRAINTS = {_ts_literal(data['enum_constraints'])} as const;\n\n"
        f"export const AXL_CANONICAL_FIELDS = {_ts_literal(data['canonical_fields'])} as const;\n\n"
        f"export const AXL_FIELD_PREFIX_GUIDANCE = {_ts_literal(data['field_prefix_guidance'])} as const;\n\n"
        f"export const AXL_SOCIAL_RX_FIELD_COMPATIBILITY = {_ts_literal(data['social_rx_field_compatibility'])} as const;\n\n"
        f"export const AXL_PREFIX_DEFAULTS = {_ts_literal(data['prefix_defaults'])} as const;\n\n"
        f"export const AXL_ID_OPTIONAL_PREFIXES = {_ts_literal(data['id_optional_prefixes'])} as const;\n\n"
        f"export const AXL_PS_ID_OPTIONAL_KINDS = {_ts_literal(data['ps_id_optional_kinds'])} as const;\n\n"
        f"export const AXL_PS_REF_REQUIRED_KINDS = {_ts_literal(data['ps_ref_required_kinds'])} as const;\n\n"
        f"export const AXL_RX_ID_OPTIONAL_STATUSES = {_ts_literal(data['rx_id_optional_statuses'])} as const;\n\n"
        f"export const AXL_STREAM_CONTINUATION_VALUES = {_ts_literal(data['stream_continuation_values'])} as const;\n"
        f"\nexport const AXL_DELTA_OPERATION_OPS = {_ts_literal(data['delta_operation_ops'])} as const;\n"
        f"\nexport const AXL_CORE_ABBREVIATIONS = {_ts_literal(data['core_abbreviations'])} as const;\n\n"
        f"export const AXL_SOCIAL_ABBREVIATIONS = {_ts_literal(data['social_abbreviations'])} as const;\n"
    )


def main() -> None:
    TARGET.write_text(_render(), encoding="utf-8")


if __name__ == "__main__":
    main()
