"""Standalone AXL Agent eXchange Language package."""

from .models import (
    AXL_CANONICAL_FIELDS,
    AXL_CANONICAL_PREFIXES,
    AXL_CORE_ABBREVIATIONS,
    AXL_DELTA_OPERATION_OPS,
    AXL_ENUM_CONSTRAINTS,
    AXL_FIELD_PREFIX_GUIDANCE,
    AXL_ID_OPTIONAL_PREFIXES,
    AXL_KIND_LABELS,
    AXL_PREFIX_DEFAULTS,
    AXL_PS_ID_OPTIONAL_KINDS,
    AXL_PS_REF_REQUIRED_KINDS,
    AXL_RX_ID_OPTIONAL_STATUSES,
    AXL_SOCIAL_ABBREVIATIONS,
    AXL_SOCIAL_RX_FIELD_COMPATIBILITY,
    AXL_STREAM_CONTINUATION_VALUES,
    AXL_V2_PREFIXES,
    AxlEnvelope,
    AxlMessage,
    AxlParseError,
    AxlPrefix,
)
from .protocol import (
    AxlTransport,
    build_axl_message,
    compose_axl_message,
    extract_abbreviation_registry,
    normalize_axl_message,
    parse_axl_message,
)

__version__ = "0.1.0"

__all__ = [
    "AXL_CANONICAL_FIELDS",
    "AXL_CANONICAL_PREFIXES",
    "AXL_CORE_ABBREVIATIONS",
    "AXL_DELTA_OPERATION_OPS",
    "AXL_ENUM_CONSTRAINTS",
    "AXL_FIELD_PREFIX_GUIDANCE",
    "AXL_ID_OPTIONAL_PREFIXES",
    "AXL_KIND_LABELS",
    "AXL_PREFIX_DEFAULTS",
    "AXL_PS_ID_OPTIONAL_KINDS",
    "AXL_PS_REF_REQUIRED_KINDS",
    "AXL_RX_ID_OPTIONAL_STATUSES",
    "AXL_SOCIAL_ABBREVIATIONS",
    "AXL_SOCIAL_RX_FIELD_COMPATIBILITY",
    "AXL_STREAM_CONTINUATION_VALUES",
    "AXL_V2_PREFIXES",
    "AxlEnvelope",
    "AxlMessage",
    "AxlParseError",
    "AxlPrefix",
    "AxlTransport",
    "build_axl_message",
    "compose_axl_message",
    "extract_abbreviation_registry",
    "normalize_axl_message",
    "parse_axl_message",
]
